# Programming Assignment

## Submitted by,
### R SREE RANJANI
### DATE OF SUBMISSION: 3/1/2022

Write a program to find the anti-complimentary sequence of an input DNA sequence. [2 marks]

In [ ]:
seq=input()
seq=list(seq)
dict_of_pairs={'A':'T','G':'C','C':'G','T':'A','a':'t','g':'c','c':'g','t':'a'}
for i in range(len(seq)):
    seq[i]=dict_of_pairs[seq[i]]
seq=seq[::-1]
print("Anti-complimentary sequence:"+"".join(seq))    


atgctaggcctaatgc
Anti-complimentary sequence:gcattaggcctagcat


Intrinsic terminators have two prominent structural features: (1) a sequence of nucleotides that includes an inverted repeat (i.e., the sequence 5'-CGGATG|CATCCG-3' contains an inverted repeat centered at the "|" because "5'-CGGATG-3"' reads "5'-CATCCG-3"' on its complementary strand), and (2) a run of roughly six uracils immediately following the inverted repeat. Write a function to identify intrinsic terminators from the sequence.	[5 marks]

In [ ]:
def computesubstrings(seq):
    n = len(seq)
    sublist = []
    for i in range(n):
        for j in range(i,n):
            if len(seq[i:j+1])>6: #to compute substrings of length greater than 6
                sublist.append(seq[i:j + 1]) 
    return sublist

def findanticomp(seq):
    seq=list(seq)
    dict_of_pairs={'A':'T','G':'C','C':'G','T':'A','a':'t','g':'c','c':'g','t':'a'}
    for i in range(len(seq)):
        seq[i]=dict_of_pairs[seq[i]]
    seq=seq[::-1]
    return("".join(seq))    

inp=input()
subarr=computesubstrings(inp)

for i in range(len(subarr)):
    if(subarr[i][-6:]=="UUUUUU"): #to check if U’s are present
        n=len(subarr[i])
        fullseq=subarr[i][-n:-6]
        fsn=len(fullseq)
        if(fsn%2==0): #to check full seq length including the anti complimentary pair is even
            hsn=fsn//2 #half seq length computation
            g=hsn+hsn
            if(subarr[i][hsn:g]==findanticomp(subarr[i][0:hsn])):
                print("Intrinsic terminator:",subarr[i])


ATTTTTTCGGATGCATCCGUUUUUUU
Intrinsic terminator: CGGATGCATCCGUUUUUU
Intrinsic terminator: CGUUUUUU


Given DNA sequence, arrange the codons in the decreasing order of frequency. [3 marks]

In [ ]:
inp=input()
codons=[]
i=0
while(i<len(inp)):
    codons.append(inp[i:i+3])
    i+=3
codon_frequency={}
for i in codons:
    try:
        codon_frequency[i]+=1
    except:
        codon_frequency[i]=1
codon_sorted_keys = sorted(codon_frequency, key=codon_frequency.get, reverse=True)
for r in codon_sorted_keys:
    print(r, codon_frequency[r])
    


ACTAGTAGGACTAGTACA
ACT 2
AGT 2
AGG 1
ACA 1


Given two strings s and t of equal length, the Hamming distance between s and t, denoted dH(s,t), is the number of corresponding symbols that differ in s and t. Write a function to compute dH(s,t)	[4 marks]

In [ ]:
def computehamming(seq1,seq2):
    DH=0
    if(len(seq1)!=len(seq2)):
        return("Enter same length sequences")
    else:
        for i in range(len(seq1)):
            if(seq1[i]!=seq2[i]):
                DH+=1
        return(DH)

            
print("Hamming distance:"+str(computehamming(input(),input())))


agctgatcagctagc
agtcgactaagctag
Hamming distance:10


Given Two protein strings s and t in FASTA format (each of length at most 100 aa), write a program to find the optimal global alignment score (use match score, mismatch and gap penalties as variables)	[10 marks]

In [ ]:
import numpy as np

def needleman_wunsch(firstseq, secondseq, match=1, mismatch=-1, gap=-1):
    dptable = np.full((len(secondseq) + 2, len(firstseq) + 2), ' ', dtype=object)
    dptable[0, 2:] = firstseq
    dptable[1, 1:] = list(range(0, -len(firstseq) - 1, -1))
    dptable[2:, 0] = secondseq
    dptable[1:, 1] = list(range(0, -len(secondseq) - 1, -1))
    is_equal = {True: match, False: mismatch}
    for f in range(2, len(firstseq) + 2):
        for s in range(2, len(secondseq) + 2):
            dptable[s, f] = max(dptable[s - 1][f - 1] + is_equal[firstseq[f - 2] == secondseq[s - 2]],
                            dptable[s - 1][f] + gap,
                            dptable[s][f - 1] + gap)
    return dptable

first_seq = "ACCTAG"
second_seq = "CCATTAG"
data = needleman_wunsch(first_seq, second_seq)
print("DP ARRAY")
print(data[1:,1:])
print("Global Allignment Score:"+str(data[len(second_seq)+1,len(first_seq)+1]))


DP ARRAY
[[0 -1 -2 -3 -4 -5 -6]
 [-1 -1 0 -1 -2 -3 -4]
 [-2 -2 0 1 0 -1 -2]
 [-3 -1 -1 0 0 1 0]
 [-4 -2 -2 -1 1 0 0]
 [-5 -3 -3 -2 0 0 -1]
 [-6 -4 -4 -3 -1 1 0]
 [-7 -5 -5 -4 -2 0 2]]
Global Allignment Score:2
